# Generated by Django 5.0.7 on 2024-07-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesdeapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("descripcion", models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name="aspirantes",
            name="teefono",
        ),
        migrations.AlterField(
            model_name="aspirantes",
            name="cel_opcional",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="gestiones",
            name="observaciones",
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="aspirantes",
            name="programa",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="cesdeapp.programa",
            ),
            preserve_default=False,
        ),
    ]
